version: '3.9'

services:
  postgres:
    image: postgres:17
    container_name: postgres-vuzioff-container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: vuzioff
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    # healthcheck:
    #   test: ["CMD-SHELL", "pg_isready -U postgres"]
    #   interval: 5s
    #   timeout: 5s
    #   retries: 5
    # restart: unless-stopped

volumes:
  postgres_data: 